export const GENRES = [
  {
    id: 'werewolf',
    emoji: '🐺',
    name: 'Werewolf',
    tagline: 'Alphas, mates & moonlit obsession',
    color: '#8B5CF6',
    accent: '#C4B5FD',
    tropes: ['Alpha & Mate Bond', 'Pack Dynamics', 'Rejection & Reclaim', 'Moon Curse', 'Fated Mates'],
    leads: { male: 'The Alpha', female: 'The Omega/Human' },
    maleNames: ['Kaden', 'Zane', 'Riven', 'Alaric', 'Theron'],
    femaleNames: ['Luna', 'Sera', 'Elara', 'Mira', 'Lyra'],
    settings: ['Pack Territory', 'Moonveil Forest', "The Alpha's Manor", 'Hidden Wolf Town', 'The Sacred Grounds'],
    conflicts: ['Rejected mate seeks revenge', 'Alpha denies the bond', 'War between packs', 'Human discovers wolf world', 'Forbidden love across rival packs'],
    openers: ['The howl split the night in two —', 'She smelled of moonflowers and danger.', 'He had rejected her once. He would not survive rejecting her again.', 'The pack gathered, and she stood at the center of it all.'],
  },
  {
    id: 'billionaire',
    emoji: '💰',
    name: 'Billionaire',
    tagline: 'Power, obsession & gilded cages',
    color: '#D97706',
    accent: '#FCD34D',
    tropes: ['Boss & Employee', 'Arranged Marriage', 'Enemies to Lovers', 'Secret Baby', 'Fake Dating'],
    leads: { male: 'The Billionaire', female: 'The Independent Woman' },
    maleNames: ['Damon', 'Xavier', 'Caelum', 'Adrian', 'Roman'],
    femaleNames: ['Marianne', 'Ariana', 'Sofia', 'Elena', 'Vivian'],
    settings: ['Manhattan Penthouse', 'Corporate HQ', 'Private Yacht', 'Milan Estate', 'The Hamptons'],
    conflicts: ['CEO obsessed with his new hire', 'Arranged marriage deal gone wrong', 'She knows his darkest secret', "He'll destroy anyone who gets close to her", "Billion-dollar bet with her heart as the prize"],
    openers: ['His name was on every magazine cover — and now it was on my contract.', 'The penthouse was cold. So was he.', "She didn't know she'd just walked into a trap.", 'He never smiled. Until her.'],
  },
  {
    id: 'mafia',
    emoji: '🥀',
    name: 'Mafia',
    tagline: 'Blood, loyalty & forbidden desire',
    color: '#DC2626',
    accent: '#FCA5A5',
    tropes: ['Don & Captive', 'Arranged Marriage to the Don', 'Rival Families', 'Bodyguard Romance', 'Runaway Bride'],
    leads: { male: 'The Don', female: "The Captive/Rival's Daughter" },
    maleNames: ['Lucian', 'Matteo', 'Dante', 'Enzo', 'Raffael'],
    femaleNames: ['Charlie', 'Isabella', 'Valentina', 'Sienna', 'Aria'],
    settings: ['Rome Villa', 'Underground Club', 'Safe House', "The Don's Estate", 'Sicily'],
    conflicts: ["She witnessed something she shouldn't have", 'He took her as collateral', 'Her father sold her to his enemy', "She's trying to escape — he won't let her", 'Two families, one deadly alliance'],
    openers: ["They said the Don never took prisoners. They were wrong — he took me.", 'Rome smelled of roses and gunpowder.', 'She ran. He let her. He always let them run first.', "The contract was signed in red. I didn't know it was blood."],
  },
];
